name: Python application

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests with coverage
              run: |
                  pytest --cov

            - name: Upload coverage report
              uses: actions/upload-artifact@v3
              with:
                  name: coverage-report
                  path: htmlcov/
